all:
  vars:
    ansible_user: azureuser
    ansible_vault_password_file: ../.vault_pass

  children:
    haproxy:
      hosts:
        vm1:
          ansible_host: hpxy.switzerlandnorth.cloudapp.azure.com
          ansible_ssh_private_key_file: ~/.ssh/hxpy.pem

    web_db:
      hosts:
        vm2:
          ansible_host: ws01.switzerlandnorth.cloudapp.azure.com
          ansible_ssh_private_key_file: ~/.ssh/ws01.pem

    web:
      hosts:
        vm3:
          ansible_host: ws02.switzerlandnorth.cloudapp.azure.com
          ansible_ssh_private_key_file: ~/.ssh/ws02.pem
